### PR TITLE
Deskpro 386/16 Revision E (8/19/1986) BIOS images and motherboard photos

### PR DESCRIPTION
**Pull request by bitslasher**
As a fan of your site and also a lover of the Compaq Deskpro computers, I'd like to contribute something special I was lucky enough to find recently.  I did my best to figure out how to use your fileimage tool (I'm not a node.js developer!).  I hope everything is in order.  I made every effort to follow your existing file naming patterns.

This commit includes properly formatted ROM images I read from a Deskpro 386 that dates from Week 37, 1986.  That's September 8th-12th!.  This is significant because Compaq announced and made the Deskpro 386 available on September 9th, 1986.  This has to be one of the earliest machines off the assembly line.  The machine's serial number is 4**637**AJ4B**0052**.  The beginning of the serial number gives the year and week ([198]6[week]37).  The system includes all the original hardware, including the EGA adapter, EGA monitor, and green mono screen.  This is certainly the earliest 386 specimen I've ever seen.  

This commit includes:

* Rev E BIOS ROM files in BIN/HEX/JSON5 formats.
* Photos of the Revision A motherboard that BIOS came with
* Updated table that lists BIOS versions to include the date

I also have original copies of the Rev F. BIOS as well.  According to your writings you pieced that together from a RAM dump.  If you're interested in ROM dumps, I can provide those as well.

### CODE REVIEW

**Review by rm-recurseforce-root — APPROVED** [review]
Sweetness!

**Comment by rm-recurseforce-root** [comment]
@jeffpar Checkout this new find!

**Comment by jeffpar** [comment]
Oh, wow, sorry I didn't notice this earlier!  This is quite a surprise.  I'll try to get this pushed out to the website tomorrow, along with a machine config to exercise the new ROM.  Thanks!

**Comment by bitslasher** [comment]
Jeff,
Would you like for me to also upload the Rev. F BIOS files?  I have another board with those ROMs also.
________________________________

**Comment by jeffpar** [comment]
Sure, if it’s not too time-consuming. It will be good to confirm that my Rev F image is legit.  Thanks.

**Comment by bitslasher** [comment]
Are you also interested in BIOSes of the Deskpro 8086 and Deskpro 286?  I'm not sure what direction you were wanting to go with things on PCJS.... I have different revisions of the original Deskpro and Deskpro 286 machines I could dump the BIOS form and contribute if you like.

--Daniel
________________________________

**Comment by bitslasher** [comment]
So it seems like Rev E was the first, from Compaq's Reference.  Isn't it odd how H.8 is out of sequence part number wise?  It seems newer...

I also wonder what the reason was for adding .X onto the letter, and not just increment the letter?

The repo seems to be missing G and H.8 if my eyes tell the truth.... I'll have to dig through my boards and see if I may have them.  I'd think maybe those would have come in the 386/20... which I don't have.  I've got /16 and /25 machines.


[cid:75cf2de2-4062-4691-b5aa-7c3f7d330b33]
________________________________

**Comment by jeffpar** [comment]
Any other DeskPro BIOSes you can dump would also be great.  I don't really have any big plans for the site, other than getting a few more hardware combinations working.  For example, as I recall, I ended up using IBM's EGA adapter ROMs with COMPAQ machines, because the COMPAQ EGA BIOS did some unexpected things that broke my emulation.  So, it would be nice to fix problems like that at some point.  If I could get working simulations of every machine (with original BIOSes) that COMPAQ produced, at least up through their 386-based machines, that would be a good (long-term) goal.  At the end of the day though, it's just a hobby.  Also, I'm going to be traveling a lot in May and June, so I'll be distracted until July.

**Comment by bitslasher** [comment]
I actually was able to spend some time with my DeskPro 286s this weekend.  I have a couple variants of the 8086 boards also, including one I think that's like 128K or something???

I have all 3 286 board types, the Magnum (2550 Type 1), Archer (2550 Type 2), and Phaser (2551)

It seems the BIOSes are compatible with both Type 1 and 2 boards.  I was able to dump the BIOS from:

P/N           Model  Board-Rev  Proc    Speed
----------- ------ ---------- ------- -----
102667-002   2550   Magnum-A    Intel     8
102669-002  

105620-001   2550   Magnum-B    Intel     8
105622-001  

109739-003   2550   Archer-D    AMD        8
109740-003  

106970-001   2551   Phaser-D    Intel    12
106971-001  

106970-002   2551   Phaser-D    AMD       12
106971-002  

109739-001   2551   Phaser-G    Intel    12
109740-001  


________________________________

**Pull request merged**
