### PR TITLE
https://www.coindesk.com/privacy/#dnsmpiUpdate README.md

### PR DESCRIPTION
**Pull request by Low8989123**
https://www.coindesk.com/privacy/#dnsmpi

### CODE REVIEW

**Comment by Low8989123** [comment]
https://www.pinterest.com/pin/523965737914214964/

**Comment by Low8989123** [comment]
https://www.pinterest.com/pin/523965737914214964/

**Review by jlcvp — CHANGES_REQUESTED** [review]
SPAM

**Comment by rm-recurseforce-root** [comment]
Per @jlcvp   closing PR

FYI @jeffpar

**Pull request closed without merging**
